mdapi/objects/Assignment__c.object
<CustomObject>
    <fields>
        <fullName>Exchange__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Exchange</label>
        <referenceTo>Exchange__c</referenceTo>
        <relationshipLabel>Assignments</relationshipLabel>
        <relationshipName>Assignments</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Recipient__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Recipient</label>
        <referenceTo>Gift_Signup__c</referenceTo>
        <relationshipLabel>Assignment</relationshipLabel>
        <relationshipName>Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Assignment</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assignments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

mdapi/objects/Exchange__c.object
<CustomObject>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Sign Ups Open</fullName>
                    <default>true</default>
                    <label>Sign Ups Open</label>
                </value>
                <value>
                    <fullName>Matching</fullName>
                </value>
                <value>
                    <fullName>Names Swapped</fullName>
                </value>
                <value>
                    <fullName>Gifts Exchanged!</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Exchange</label>
    <nameField>
        <label>Exchange Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exchanges</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

mdapi/objects/Gift_Signup__c.object
<CustomObject>
    <fields>
        <fullName>Exchange__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Exchange</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Must be an active exchange. Please contact exchange admin.</errorMessage>
            <filterItems>
                <field>Exchange__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Exchange__c</referenceTo>
        <relationshipLabel>Gift Signups</relationshipLabel>
        <relationshipName>Gift_Signups</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Gift Signup</label>
    <nameField>
        <label>Gift Signup Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Gift Signups</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

dxdev/main/default/classes/MatchingService.cls
public class MatchingService {

    public class MatchingServiceException extends Exception {}

    public static List<Gift_Signup__c> querySignups(Exchange__c ex) {
        List<Gift_Signup__c> signups = new List<Gift_Signup__c>();
        // conditional for security review
        if(Schema.sObjectType.Gift_Signup__c.isAccessible()
           && ex != null
           && ex.Id != null
        ) {
            signups = [
                SELECT  Id, OwnerId
                FROM    Gift_Signup__c
                WHERE   Exchange__c =:ex.Id
            ];
        }
        return signups; 
    }

    // Match maker, match maker make me a match!
    public static void createAssignments(Exchange__c ex) {
		
        // assignments will be added to this collection
        List<Assignment__c> assignments = new List<Assignment__c>();

        // grab list of signUps
        List<Gift_Signup__c> signUps = querySignups(ex);

        // check if you found it or if the exchange has sign ups
        if(ex == null || signUps == null || signUps.isEmpty()) {

            System.debug('Something went wrong...');

            if(ex == null) {
                throw new MatchingServiceException('did not find the exchange');
            } else if(signUps == null || signUps.isEmpty()) {
                throw new MatchingServiceException('No one is signed up for this exchange');
            }

        } else {
            // large conditional for security review
            if(Schema.sObjectType.Gift_Signup__c.fields.OwnerId.isAccessible()
               && Schema.sObjectType.Exchange__c.isUpdateable()
               && Schema.sObjectType.Exchange__c.fields.Stage__c.isUpdateable()
               && Schema.sObjectType.Assignment__c.isCreateable()
               && Schema.sObjectType.Assignment__c.fields.OwnerId.isCreateable()
               && Schema.sObjectType.Assignment__c.fields.Recipient__c.isCreateable()
               && Schema.sObjectType.Assignment__c.fields.Exchange__c.isCreateable()
            ) {
                // grab signups size
                Integer signUpSize = signUps.size()+0;
    
                // return matches
                List<Integer> matched = RandomUtil.shuffleMatch(signUpSize);
    
                // assign
                for(Integer i = 0; i < signUpSize; i++) {
                    assignments.add(new Assignment__c (
                        OwnerId = signUps.get(i).OwnerId,
                        Recipient__c = signUps.get(matched.get(i)).Id,
                        Exchange__c = ex.Id
                    ));
                }
    
                // if there are assignments, insert them
                if(assignments != null && !assignments.isEmpty()) {
                    System.debug('Creating ' + assignments.size()+ ' assignments');
                    insert assignments;
                    System.debug('Successfully created assignments!');
                    ex.Stage__c = 'Names Swapped';
                }
            }
        }
    }
}