mdapi/objects/Assignment__c.object
<CustomObject>
    <fields>
        <fullName>Exchange__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Exchange</label>
        <referenceTo>Exchange__c</referenceTo>
        <relationshipLabel>Assignments</relationshipLabel>
        <relationshipName>Assignments</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Assignment</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assignments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

mdapi/objects/Exchange__c.object
<CustomObject>
    <fields>
        <fullName>Email_Template_Name__c</fullName>
        <defaultValue>&quot;Exchange 7 Day Notice&quot;</defaultValue>
        <description>Not used in this version :)</description>
        <label>Email Template Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Exchange</label>
    <nameField>
        <label>Exchange Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exchanges</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

mdapi/classes/EmailReminder.cls
public with sharing class EmailReminder {

    private ApexPages.StandardController standardController;

    public Id exchangeId {get; set;}

    public EmailReminder(ApexPages.StandardController standardController) {
        this.standardController = standardController;
        exchangeId  = ApexPages.CurrentPage().getparameters().get('id');
        System.debug('The exchange record: ' + exchangeId);
    }

    public PageReference sendEmail() {
        // conditional for security review
        if(Schema.sObjectType.Assignment__c.fields.OwnerId.isAccessible()
           && Schema.sObjectType.Exchange__c.fields.Email_Template_Name__c.isAccessible()
           && Schema.sObjectType.EmailTemplate.fields.Id.isAccessible()
        ) {
            List<Assignment__c> listUsers = [
                SELECT
                    OwnerId 
                FROM 
                    Assignment__c
                WHERE
                    Exchange__c =: exchangeId 
            ];
    
            List<Id> listIds = new List<Id>();
            System.debug(listUsers.size());
    
            for(Assignment__c a:listUsers) {
                listIds.add(a.OwnerId);
                system.debug(a.OwnerId);
            }
    
            String emailTemplateName = 'Sales: New Customer Email';
    
            List<Exchange__c> templateNameOnExchange = [
                SELECT
                    Email_Template_Name__c
                FROM
                    Exchange__c 
                WHERE
                    Id =: exchangeId
            ];
    
            if(templateNameOnExchange != null && !templateNameOnExchange.isEmpty()) {
                emailTemplateName = templateNameOnExchange[0].Email_Template_Name__c;
            }

            EmailTemplate et = [
                SELECT
                    Id
                FROM
                    EmailTemplate
                WHERE
                    Name =: emailTemplateName 
                LIMIT 1
            ];

            Messaging.MassEmailMessage mail = new Messaging.MassEmailMessage();
            mail.setTargetObjectIds(listIds);
            mail.setSenderDisplayName('Gift Exchange Admin');
            mail.setTemplateId(et.Id);
            mail.setSaveAsActivity(false);
            Messaging.sendEmail(new Messaging.MassEmailMessage[] { mail });
        }

		PageReference pageRef = new PageReference('/' + exchangeId);
        pageRef.setRedirect(true);

        // Redirects to Exchange page
        return pageRef;
    }
}