mdapi/objects/Assignment__c.object
<CustomObject>
    <fields>
        <fullName>Exchange__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Exchange</label>
        <referenceTo>Exchange__c</referenceTo>
        <relationshipLabel>Assignments</relationshipLabel>
        <relationshipName>Assignments</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Assignment</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assignments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

mdapi/objects/Exchange__c.object
<CustomObject>
    <fields>
        <fullName>Exchange_Admin__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This is the user who will be running the exchange going forward. Make sure they have the right permission sets!</inlineHelpText>
        <label>Exchange Admin</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Exchanges</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Exchange_Date__c</fullName>
        <inlineHelpText>This is the deadline that all of the gifts need to be received by</inlineHelpText>
        <label>Exchange Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Sign Ups Open</fullName>
                    <default>true</default>
                    <label>Sign Ups Open</label>
                </value>
                <value>
                    <fullName>Matching</fullName>
                </value>
                <value>
                    <fullName>Names Swapped</fullName>
                </value>
                <value>
                    <fullName>Gifts Exchanged!</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Exchange</label>
    <nameField>
        <label>Exchange Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exchanges</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

mdapi/objects/Gift_Signup__c.object
<CustomObject>
    <fields>
        <fullName>Exchange__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Exchange</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Must be an active exchange. Please contact exchange admin.</errorMessage>
            <filterItems>
                <field>Exchange__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Exchange__c</referenceTo>
        <relationshipLabel>Gift Signups</relationshipLabel>
        <relationshipName>Gift_Signups</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Gift Signup</label>
    <nameField>
        <label>Gift Signup Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Gift Signups</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/TestClass.cls
@isTest
private class TestClass {

    static testMethod void testEverything() {
        
		Profile p = [
            SELECT
                Id
            FROM
                Profile
            WHERE
                Name ='System Administrator' 
            LIMIT 1
        ];

		UserRole ur = [
            SELECT
                Id,
                Name
            FROM
                UserRole
            WHERE
                Name = 'CEO'
            LIMIT 1
        ];

        String x_name = 'bobjones';
        
		User u = new User(
	        alias = x_name.substring(0,7),
	        email = x_name + '=test.com@example.com',
	        emailencodingkey = 'UTF-8', 
            UserRoleId = ur.Id,
	        lastname = x_name,
	        languagelocalekey = 'en_US',
	        localesidkey = 'en_US', 
	        profileid = p.Id,
	        timezonesidkey = 'America/Chicago', 
	        username = x_name+'=test.com@example.com.testing'
		);
        
        insert u;

        System.runAs(u) {

			Test.startTest();
            
            Exchange__c testExchange = new Exchange__c(
                Exchange_Admin__c = UserInfo.getUserId(),
                Exchange_Date__c = System.today()
            );
            insert testExchange;
            System.debug(testExchange.Id);
            
            Assignment__c testAssignment = new Assignment__c(
                Exchange__c = testExchange.Id,
                OwnerId = UserInfo.getUserId()
            );
            insert testAssignment; 
            System.debug(testAssignment.OwnerId);

            Apexpages.StandardController sc = new Apexpages.StandardController(testExchange);

            EmailReminder em = new emailReminder(sc); 
            em.exchangeId = testExchange.Id;
            System.debug('Exchange ID ' + testExchange.Id);

            PageReference pageRef = em.sendEmail();

            List<Gift_Signup__c> signups = new List<Gift_Signup__c>();

            for(Integer i = 0; i < 5; i++) {
                signups.add(new Gift_Signup__c(
                    Exchange__c = testExchange.Id
                ));
            }

            insert signups;

            testExchange.Stage__c = 'Matching';
            update testExchange;
            
            testExchange = null;
            
            delete signups;

            try {
            	MatchingService.createAssignments(testExchange);    
            } catch(Exception e) { }
            
            testExchange = null;
            
            try {
            	MatchingService.createAssignments(testExchange);  
            } catch(Exception e) { }

            Test.stopTest();
        }
    }
}